#!/usr/bin/env bash
#
# Generate a coverage inventory across every test suite in the repo and print it as Markdown.
# Source of truth for "what is covered" (issue #54). Regenerate with `make test-inventory`,
# which writes docs/test-inventory.md — that file is generated, do not hand-edit it.
#
# Static (grep-based): no test run, no dependencies, deterministic — so it never drifts from
# whether a daemon/server happens to be available.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 1

# Test functions (def test_… / async def test_…) in a python file, in source order.
py_tests() {
    grep -E '^[[:space:]]*(async[[:space:]]+)?def test_' "$1" 2>/dev/null |
        sed -E 's/^[[:space:]]*(async[[:space:]]+)?def (test_[A-Za-z0-9_]+).*/\2/'
}
# test('name' | test("name") cases in a node test file.
node_tests() { grep -oE "test\((['\"])[^'\"]+\1" "$1" 2>/dev/null | sed -E "s/^test\(['\"]//; s/['\"]$//"; }
# `== section ==` headers in a shell suite.
sh_sections() { grep -oE '== [^=]+ ==' "$1" 2>/dev/null | sed -E 's/^== //; s/ ==$//'; }
count() { grep -c . 2>/dev/null || true; }

# Print "- name" bullets for each line on stdin.
bullets() { sed 's/^/- /'; }

# --- gather ---------------------------------------------------------------
PY_DASH_FILES=$(find build/dashboard/tests -name 'test_*.py' | sort)
PY_FAKE_FILE="tests/integration/fakes/test_contract.py"
NODE_FILES=$(find build/dashboard/tests/frontend -name '*.test.mjs' 2>/dev/null | sort)

n_py_dash=0
for f in $PY_DASH_FILES; do n_py_dash=$((n_py_dash + $(py_tests "$f" | count))); done
n_py_fake=$(py_tests "$PY_FAKE_FILE" | count)
n_node=0
for f in $NODE_FILES; do n_node=$((n_node + $(node_tests "$f" | count))); done
n_stack=$(sh_sections tests/stack/run.sh | count)
n_selftest=$(sh_sections tests/integration/selftest.sh | count)
n_scen=$(awk -F'\t' 'NF>1{print $1}' <(sed -n '/scenario_matrix() {/,/^EOF/p' tests/integration/scenarios.sh | grep -E '\t') | count)
n_axes=$(grep -cE '=' <(sed -n '/axis_coverage() {/,/^EOF/p' tests/integration/scenarios.sh | grep -E '^[a-z].*='))
n_mini=$(grep -cE 'log "scenario [0-9]' tests/integration/mini-stack/run-mini-stack.sh)

total=$((n_py_dash + n_py_fake + n_node + n_stack + n_selftest + n_scen + n_mini))

# --- emit -----------------------------------------------------------------
cat <<EOF
# Test Inventory

_Generated by \`make test-inventory\` ([\`tests/inventory.sh\`](../tests/inventory.sh)). **Do not
edit by hand** — re-run the target to refresh. See [Testing Strategy](testing-strategy.md) for
how the tiers fit together._

**Totals:** ${n_py_dash} dashboard unit tests · ${n_py_fake} contract tests · ${n_node} frontend
tests · ${n_stack} \`pithead\` shell sections · ${n_selftest} harness self-test sections ·
${n_scen} live config scenarios (${n_axes} axis values) · ${n_mini} mini-stack scenarios.

> Counts are **test functions / named cases** (parametrized pytest cases expand to more at
> run time — e.g. the dashboard suite collects ~381). Generated statically by grep, so it's
> stable regardless of what's installed.

| Tier | Suite | Cases |
|---|---|---|
| 1 — Unit | dashboard pytest | ${n_py_dash} |
| 1 — Unit | frontend (node --test) | ${n_node} |
| 1 — Unit | \`pithead\` shell suite | ${n_stack} sections |
| 1 — Unit | compose interpolation + hardening (#90) | 1 |
| 2 — Contract | fake-daemon clients | ${n_py_fake} |
| 3 — Mini-stack | docker control-plane scenarios | ${n_mini} |
| 4 — Live matrix | config scenarios | ${n_scen} (${n_axes} axis values) |
| 4 — Live matrix | harness self-test | ${n_selftest} sections |

---

## Tier 1 — Unit & component

### Dashboard (pytest) — ${n_py_dash} tests
EOF

for f in $PY_DASH_FILES; do
    n=$(py_tests "$f" | count)
    printf '\n#### %s — %s\n' "${f#build/dashboard/}" "$n"
    py_tests "$f" | bullets
done

cat <<EOF

### Frontend logic (node --test) — ${n_node} tests
EOF
for f in $NODE_FILES; do node_tests "$f" | bullets; done

cat <<EOF

### \`pithead\` shell suite (tests/stack/run.sh) — ${n_stack} sections
EOF
sh_sections tests/stack/run.sh | bullets

cat <<EOF

### Compose validation + hardening (tests/stack/test_compose.sh)
- docker-compose.yml \`\${VAR}\` interpolation resolves against a representative .env
- #90 hardening invariants: no-new-privileges / cap_drop / read-only roots, credential-free
  healthchecks, least-privilege Docker socket proxies, and the pinned \`pithead\` project name

## Tier 2 — Contract (real clients vs controllable fakes)

### tests/integration/fakes/test_contract.py — ${n_py_fake} tests
EOF
py_tests "$PY_FAKE_FILE" | bullets

cat <<EOF

## Tier 3 — Fake-daemon mini-stack (docker)

### tests/integration/mini-stack/run-mini-stack.sh — ${n_mini} scenarios
EOF
grep -oE 'log "scenario [0-9]+: [^"]+"' tests/integration/mini-stack/run-mini-stack.sh |
    sed -E 's/^log "//; s/"$//' | bullets

cat <<EOF

## Tier 4 — Live config matrix (real synced server)

### Config scenarios (tests/integration/scenarios.sh) — ${n_scen}
EOF
sed -n '/scenario_matrix() {/,/^EOF/p' tests/integration/scenarios.sh |
    grep -E $'\t' | awk -F'\t' '{print $1}' | bullets

cat <<EOF

### Axis coverage (every value exercised at least once) — ${n_axes}
EOF
sed -n '/axis_coverage() {/,/^EOF/p' tests/integration/scenarios.sh | grep -E '^[a-z].*=' | bullets

cat <<EOF

### Per-scenario assertions (tests/integration/run.sh)
EOF
grep -hoE '(assert_[a-z_]+|it_pass) "[^"]+"' tests/integration/run.sh |
    sed -E 's/^(assert_[a-z_]+|it_pass) "//; s/"$//' |
    grep -vE '^\$[A-Za-z_]+$' | sort -u | bullets

cat <<EOF

### Harness self-test (tests/integration/selftest.sh) — ${n_selftest} sections
EOF
sh_sections tests/integration/selftest.sh | bullets

cat <<EOF

---

_Grand total: **${total}** enumerated cases/sections across the four tiers (plus the live
lifecycle and fault-injection phases, which are exercised on a real server)._
EOF
