#!/usr/bin/env bash
# The file-budget ratchet gate (#1105 Phase 0): stop the biggest files in the repo from getting
# any bigger, without demanding anyone rewrite them today. Two rules:
#
#   1. A tracked file over the 400-line target must record a ceiling in
#      docs/dev/file-budget.tsv; over 800 the refusal names the hard ceiling instead.
#   2. An existing offender (already over 400 when this gate landed, or added to the budget
#      since) gets its CURRENT line count recorded in docs/dev/file-budget.tsv as a personal
#      ceiling. A PR may not grow that file past its recorded ceiling. Ceilings only ever go
#      DOWN — this script rejects any budget edit that raises one (checked against the base
#      branch, $BASE_REF below) — and a file that shrinks back to <=400 must drop its entry.
#
# Exemptions are enumerated by path/glob in is_exempt() below, each with its own reason —
# generated code, vendored files, data/config, prose docs, and the shipped `pithead` artifact
# itself, which #1105 Phase 2 made a build product: it is generated from lib/pithead/*.sh, and
# those slices carry the rows. Binary files are detected generically (grep -I), not listed.
#
# Run `--self-test` first (fixtures for every failure mode, including the empty-enumeration
# guard); `--generate` reprints the budget for every current non-exempt offender, for seeding or
# refreshing the file by hand — it never writes the file itself and never lowers the bar for you.
set -euo pipefail

TARGET_LINES=400
HARD_CEILING=800
BUDGET_FILE="docs/dev/file-budget.tsv"

# The branch this PR ratchets against — the twin lane it will merge into, NOT a fixed branch.
# develop-v2 carries develop's whole history plus the appliance code, so the same files are
# legitimately LARGER there; ratcheting a develop-v2 PR against origin/develop would reject
# every one of those larger ceilings as an illegal "raise". The lane is a property of the
# branch's HISTORY, never of being level with the lane tip: a develop-v2 branch carries
# v2-only commits in its merge-base with develop-v2, and develop's own history never does.
# The previous rule (is the lane TIP an ancestor of HEAD) false-REDded every in-flight
# develop-v2 branch the moment any other merge moved the lane. Each candidate
# falls back to its bare local name; if nothing resolves the monotonic check is skipped
# with a loud note.
resolve_base_ref() {
    local v2 dev mb
    for v2 in origin/develop-v2 develop-v2; do
        git rev-parse -q --verify "$v2" >/dev/null 2>&1 || continue
        mb=$(git merge-base HEAD "$v2" 2>/dev/null) || mb=""
        [ -n "$mb" ] || break
        for dev in origin/develop develop; do
            git rev-parse -q --verify "$dev" >/dev/null 2>&1 || continue
            if git merge-base --is-ancestor "$mb" "$dev" 2>/dev/null; then
                echo "$dev"
            else
                echo "$v2"
            fi
            return 0
        done
        # develop-v2 exists but no develop ref at all: v2-lane by elimination.
        echo "$v2"
        return 0
    done
    for dev in origin/develop develop; do
        if git rev-parse -q --verify "$dev" >/dev/null 2>&1; then
            echo "$dev"
            return 0
        fi
    done
    echo ""
}

# A broken enumeration and a genuinely clean tree both read as "zero hits" — refuse to treat an
# empty candidate list as success. Mirrors lint-topology-classes.sh's own guard.
enforce_nonempty_enumeration() {
    if [ "$(git ls-files | wc -l)" -eq 0 ]; then
        echo "FATAL: git ls-files enumerated zero tracked files. A broken enumeration and a" >&2
        echo "clean tree both scan zero hits — refusing to report either as success." >&2
        return 1
    fi
    return 0
}

# --- exemptions, one glob per reason (case pattern matching: '*' matches '/' too) ---------------
is_exempt() {
    case "$1" in
    # Generated protobuf/gRPC stubs — regenerated by a documented docker command
    # (client/tari/Readme.md), never hand-edited.
    dashboard/mining_dashboard/client/tari/generated/*) return 0 ;;
    *_pb2*) return 0 ;;
    # Vendored .proto interface definitions copied from the upstream Tari project (each file
    # carries Tari's own copyright header) — not authored in this repo.
    dashboard/mining_dashboard/client/tari/proto/*) return 0 ;;
    # Vendored third-party JS (preact/htm/hammer/chartjs-plugin-zoom) — see vendor/README.md.
    dashboard/mining_dashboard/web/static/vendor/*) return 0 ;;
    # Data/config, not source to split: the compose file, dependency lockfiles, JSON
    # fixtures/config (including config.reference.json and test fixtures).
    docker-compose.yml) return 0 ;;
    *.lock) return 0 ;;
    *.json) return 0 ;;
    # Prose documentation, including CHANGELOG.md — it grows by nature (one entry per release)
    # and already carries its own voice/accuracy gate (lint-docs-voice); this gate governs
    # source code, matching #1105's own "files of concern" table (source files only).
    *.md) return 0 ;;
    # The XvB delivery study's research material: vendored external source snapshots, captured
    # data, and one-off analysis scripts — not part of the shipped product.
    docs/research/*) return 0 ;;
    # Captured benchmark run data, not source.
    docs/benchmarks/data/*) return 0 ;;
    # The shipped pithead CLI artifact — generated, not written (#1105 Phase 2): it is built from
    # lib/pithead/*.sh, and those slices carry the budget rows instead.
    pithead) return 0 ;;
    *) return 1 ;;
    esac
}

# grep -I treats a binary file as non-matching instead of reading it as text; an empty file
# never matches either, but an empty file also never trips a line-count ceiling, so folding the
# two together is safe. Skips images and other binary blobs generically, no path list needed.
is_binary_or_empty() {
    ! LC_ALL=C grep -Iq . "$1" 2>/dev/null
}

# Count lines by record, not by trailing newline (`wc -l` undercounts a file with no final
# newline by one — exactly the off-by-one a mutation proof would otherwise hide).
count_lines() {
    awk 'END { print NR + 0 }' "$1" 2>/dev/null || echo 0
}

# Every tracked, non-exempt, non-binary file: "path<TAB>lines", one per line.
list_candidates() {
    local f
    git ls-files | while IFS= read -r f; do
        [ -f "$f" ] || continue
        is_exempt "$f" && continue
        is_binary_or_empty "$f" && continue
        printf '%s\t%s\n' "$f" "$(count_lines "$f")"
    done
}

# Parse a budget file (path<TAB>ceiling, '#' comments and blank lines skipped) from stdin.
parse_budget() {
    grep -vE '^[[:space:]]*(#|$)' | awk -F'\t' 'NF==2 {print $1"\t"$2}'
}

# --- the gate itself --------------------------------------------------------------------------
run_gate() {
    local fail=0 path lines ceiling budget_lines
    enforce_nonempty_enumeration || return 1

    budget_lines=$([ -f "$BUDGET_FILE" ] && parse_budget <"$BUDGET_FILE" || true)

    local candidates
    candidates=$(list_candidates)
    if [ -z "$candidates" ]; then
        echo "FATAL: the candidate scan (git ls-files, minus exemptions/binaries) returned zero" >&2
        echo "files. That is never a legitimately clean result for this tree — refusing to pass." >&2
        return 1
    fi

    while IFS=$'\t' read -r path lines; do
        [ -n "$path" ] || continue
        ceiling=$(printf '%s\n' "$budget_lines" | awk -F'\t' -v p="$path" '$1==p {print $2; exit}')
        if [ -n "$ceiling" ]; then
            if [ "$lines" -gt "$ceiling" ]; then
                echo "file-budget: FAIL — $path is $lines lines, over its recorded ceiling of $ceiling ($BUDGET_FILE)."
                fail=1
            elif [ "$lines" -le "$TARGET_LINES" ]; then
                echo "file-budget: FAIL — $path is $lines lines (<= $TARGET_LINES target) but still has a" \
                    "$BUDGET_FILE entry (ceiling $ceiling). Remove the entry."
                fail=1
            fi
        elif [ "$lines" -gt "$HARD_CEILING" ]; then
            echo "file-budget: FAIL — $path is $lines lines, over the hard ceiling of $HARD_CEILING for a" \
                "new/unbudgeted file (target: $TARGET_LINES)."
            fail=1
        elif [ "$lines" -gt "$TARGET_LINES" ]; then
            # The other half of the same rule: an entry IFF over target. --generate has always
            # emitted exactly this set (`awk '$2 > t'`); the gate now refuses what it would write.
            echo "file-budget: FAIL — $path is $lines lines (> $TARGET_LINES target) but has no" \
                "$BUDGET_FILE entry. Add one: scripts/lint-file-budget.sh --generate."
            fail=1
        fi
    done <<<"$candidates"

    # Every budget entry must name a real, currently-exempt-free, over-target file — a stale
    # entry (deleted, renamed, or exempted since) hides drift instead of proving anything.
    while IFS=$'\t' read -r path ceiling; do
        [ -n "$path" ] || continue
        if [ ! -f "$path" ] || is_exempt "$path"; then
            echo "file-budget: FAIL — $BUDGET_FILE lists '$path', which no longer exists (or is now" \
                "exempt). Remove the entry."
            fail=1
        fi
    done <<<"$budget_lines"

    check_monotonic || fail=1

    if [ "$fail" -ne 0 ]; then
        echo "See CONTRIBUTING.md — file budget gate."
        return 1
    fi
    echo "file budget OK — every over-target file has a ceiling, none grew past it, $BUDGET_FILE is monotonic."
    return 0
}

# Ceilings only ever go down. Compare the working-tree budget against the base branch's: any
# path present in both whose ceiling ROSE is a rejected edit, proving the ratchet is real.
check_monotonic() {
    local base old_lines fail=0 path old_ceiling new_ceiling
    base=$(resolve_base_ref)
    if [ -z "$base" ]; then
        echo "file-budget: NOTE — no base ref (origin/develop or develop) resolvable; skipping the" \
            "monotonic-ceiling check. This never happens in CI." >&2
        return 0
    fi
    [ -f "$BUDGET_FILE" ] || return 0
    old_lines=$(git show "$base:$BUDGET_FILE" 2>/dev/null | parse_budget || true)
    [ -n "$old_lines" ] || return 0

    while IFS=$'\t' read -r path old_ceiling; do
        [ -n "$path" ] || continue
        new_ceiling=$(parse_budget <"$BUDGET_FILE" | awk -F'\t' -v p="$path" '$1==p {print $2; exit}')
        if [ -n "$new_ceiling" ] && [ "$new_ceiling" -gt "$old_ceiling" ]; then
            echo "file-budget: FAIL — $BUDGET_FILE raises $path's ceiling from $old_ceiling to" \
                "$new_ceiling. Ceilings only go down."
            fail=1
        fi
    done <<<"$old_lines"
    return "$fail"
}

# Reprint the budget the current tree implies (every non-exempt file over target). Never writes
# the file — review the diff and commit it by hand, same as any other ratchet edit.
generate_budget() {
    printf '%s\n' \
        '# Generated by scripts/lint-file-budget.sh --generate. See this script header for the' \
        '# target/ceiling rationale and CONTRIBUTING.md for the gate.'
    printf '# path<TAB>ceiling-in-lines. Ceilings only ever go down; a file at or below %s lines drops its entry.\n' \
        "$TARGET_LINES"
    list_candidates | awk -F'\t' -v t="$TARGET_LINES" '$2 > t {print}' | sort
}

# --- self-test: every failure mode against fixtures, in an isolated throwaway git repo ----------
self_test() {
    local tmp out st_fail=0 rc=0
    tmp=$(mktemp -d)
    out=$(mktemp)
    # Double-quoted so $tmp/$out are embedded now, as literal paths — the trap still fires after
    # self_test's own locals have gone out of scope, so a deferred expansion would see them unset.
    # shellcheck disable=SC2064
    trap "rm -rf '$tmp' '$out'" EXIT
    git -C "$tmp" init -q -b develop
    git -C "$tmp" config user.email test@example.invalid
    git -C "$tmp" config user.name test

    expect() { # <desc> <expected-rc> <actual-rc>
        if [ "$2" -eq "$3" ]; then
            echo "  self-test ok: $1"
        else
            echo "  self-test FAIL: $1 (expected rc $2, got $3)"
            st_fail=1
        fi
    }
    seq 1 500 >"$tmp/budgeted.sh"
    mkdir -p "$tmp/$(dirname "$BUDGET_FILE")"
    printf '# test budget\nbudgeted.sh\t500\n' >"$tmp/$BUDGET_FILE"
    git -C "$tmp" add budgeted.sh "$BUDGET_FILE"
    git -C "$tmp" commit -q -m base

    rc=0
    (cd "$tmp" && run_gate) >"$out" 2>&1 || rc=$?
    expect "calibration: budgeted file at its ceiling passes" 0 "$rc"

    seq 1 501 >"$tmp/budgeted.sh"
    rc=0
    (cd "$tmp" && run_gate) >"$out" 2>&1 || rc=$?
    expect "growing a budgeted file past its ceiling FAILS" 1 "$rc"
    if grep -q "budgeted.sh is 501" "$out"; then
        echo "  self-test ok: names the offending file"
    else
        echo "  self-test FAIL: did not name the offending file"
        st_fail=1
    fi

    seq 1 500 >"$tmp/budgeted.sh"
    rc=0
    (cd "$tmp" && run_gate) >"$out" 2>&1 || rc=$?
    expect "reverting the growth passes again" 0 "$rc"

    seq 1 800 >"$tmp/new.sh"
    git -C "$tmp" add new.sh
    rc=0
    (cd "$tmp" && run_gate) >"$out" 2>&1 || rc=$?
    expect "an over-target file with NO entry FAILS (800, inside the hard ceiling)" 1 "$rc"
    if grep -q "new.sh is 800 lines (> 400 target) but has no" "$out"; then
        echo "  self-test ok: names the missing entry, not the hard ceiling"
    else
        echo "  self-test FAIL: did not name the missing entry"
        st_fail=1
    fi
    printf '# test budget\nbudgeted.sh\t500\nnew.sh\t800\n' >"$tmp/$BUDGET_FILE"
    rc=0
    (cd "$tmp" && run_gate) >"$out" 2>&1 || rc=$?
    expect "recording the entry is the fix — the same file then passes" 0 "$rc"
    printf '# test budget\nbudgeted.sh\t500\n' >"$tmp/$BUDGET_FILE"
    seq 1 801 >"$tmp/new.sh"
    rc=0
    (cd "$tmp" && run_gate) >"$out" 2>&1 || rc=$?
    expect "a new 801-line file FAILS the hard ceiling" 1 "$rc"
    rm -f "$tmp/new.sh"
    git -C "$tmp" rm -q --cached new.sh >/dev/null 2>&1 || true

    printf '# test budget\nbudgeted.sh\t400\n' >"$tmp/$BUDGET_FILE"
    rc=0
    (cd "$tmp" && run_gate) >"$out" 2>&1 || rc=$?
    expect "lowering a ceiling below the file's real size FAILS (reality check)" 1 "$rc"

    printf '# test budget\nbudgeted.sh\t900\n' >"$tmp/$BUDGET_FILE"
    rc=0
    (cd "$tmp" && run_gate) >"$out" 2>&1 || rc=$?
    expect "raising a ceiling FAILS (monotonicity, vs the committed base)" 1 "$rc"
    if grep -q "raises budgeted.sh's ceiling" "$out"; then
        echo "  self-test ok: names the ceiling raise"
    else
        echo "  self-test FAIL: did not name the ceiling raise"
        st_fail=1
    fi
    printf '# test budget\nbudgeted.sh\t500\n' >"$tmp/$BUDGET_FILE"

    seq 1 300 >"$tmp/budgeted.sh"
    rc=0
    (cd "$tmp" && run_gate) >"$out" 2>&1 || rc=$?
    expect "a budgeted file dropped below target still listed FAILS (stale entry)" 1 "$rc"
    seq 1 500 >"$tmp/budgeted.sh"

    # Two-lane shape: a develop-v2 branch cut BEFORE the lane tip advanced must still
    # ratchet against develop-v2, not fall back to develop and read this lane's larger
    # ceiling as a raise — the false RED that bit two live PRs the day the tip moved.
    local tmp3
    tmp3=$(mktemp -d)
    git -C "$tmp3" init -q -b develop
    git -C "$tmp3" config user.email test@example.invalid
    git -C "$tmp3" config user.name test
    mkdir -p "$tmp3/$(dirname "$BUDGET_FILE")"
    seq 1 500 >"$tmp3/budgeted.sh"
    printf '# test budget\nbudgeted.sh\t500\n' >"$tmp3/$BUDGET_FILE"
    git -C "$tmp3" add -A && git -C "$tmp3" commit -q -m dev-base
    git -C "$tmp3" checkout -q -b develop-v2
    seq 1 600 >"$tmp3/budgeted.sh"
    printf '# test budget\nbudgeted.sh\t600\n' >"$tmp3/$BUDGET_FILE"
    git -C "$tmp3" add -A && git -C "$tmp3" commit -q -m v2-larger
    git -C "$tmp3" checkout -q -b feature
    git -C "$tmp3" checkout -q develop-v2
    echo x >"$tmp3/other.txt"
    git -C "$tmp3" add other.txt && git -C "$tmp3" commit -q -m v2-advances
    git -C "$tmp3" checkout -q feature
    seq 1 580 >"$tmp3/budgeted.sh"
    printf '# test budget\nbudgeted.sh\t580\n' >"$tmp3/$BUDGET_FILE"
    rc=0
    (cd "$tmp3" && run_gate) >"$out" 2>&1 || rc=$?
    expect "a v2-lane branch behind the moved lane tip still ratchets against develop-v2" 0 "$rc"
    rc=0
    (cd "$tmp3" && [ "$(resolve_base_ref)" = develop-v2 ]) || rc=1
    expect "lane detection reads history, not tip-levelness" 0 "$rc"
    git -C "$tmp3" checkout -q -f develop
    rc=0
    (cd "$tmp3" && [ "$(resolve_base_ref)" = develop ]) || rc=1
    expect "a develop-lane checkout still resolves to develop" 0 "$rc"
    rm -rf "$tmp3"

    rc=0
    (
        cd "$tmp" || exit 90
        list_candidates() { :; }
        run_gate
    ) >"$out" 2>&1 || rc=$?
    expect "an empty candidate scan FAILS loudly, never a vacuous pass" 1 "$rc"

    local tmp2
    tmp2=$(mktemp -d)
    git -C "$tmp2" init -q -b develop
    git -C "$tmp2" config user.email test@example.invalid
    git -C "$tmp2" config user.name test
    rc=0
    (cd "$tmp2" && run_gate) >"$out" 2>&1 || rc=$?
    expect "a repo with zero tracked files FAILS loudly (enumeration guard)" 1 "$rc"
    rm -rf "$tmp2"

    if [ "$st_fail" -eq 0 ]; then
        echo "lint-file-budget self-test OK"
        return 0
    fi
    echo "lint-file-budget self-test FAILED"
    return 1
}

case "${1:-}" in
--self-test)
    self_test
    exit $?
    ;;
--generate)
    generate_budget
    exit 0
    ;;
"")
    run_gate
    exit $?
    ;;
*)
    echo "usage: $0 [--self-test|--generate]" >&2
    exit 2
    ;;
esac
